Repository octokit/graphql.js, pull requests merged in 2020-05, with the labels that each got.

#87 Using named imports with necessary dependencies
  README.md
  src/graphql.ts
  src/index.ts
  src/types.ts
  src/with-defaults.ts
  test/defaults.test.ts
  test/error.test.ts
  test/graphql.test.ts
  test/with-custom-request.test.ts
Labels: maintenance

#84 feat: add `mediaType` to non variable options
  package-lock.json
  src/error.ts
  src/graphql.ts
  src/types.ts
  test/graphql.test.ts
Labels: feature

#89 ci: replace travis with GitHub Actions
  .github/workflows/release.yml
  .github/workflows/test.yml
  .github/workflows/update-prettier.yml
  .gitignore
  .travis.yml
  README.md
Labels: maintenance

#93 Replace Greenkeeper with Dependabot
  .github/dependabot.yml
  .github/workflows/test.yml
  .github/workflows/update-prettier.yml
  README.md
Labels: maintenance

#99 feat(typescript): add generic support to graphql
  src/error.ts
  src/graphql.ts
  src/types.ts
  src/with-defaults.ts
Labels: feature, typescript
