Repository octokit/graphql.js, pull requests merged in 2022-07, with the labels that each got.

#365 ci: stop testing against NodeJS v10, v12
  .github/workflows/test.yml
  package.json
Labels: blocked, maintenance

#369 ci(test): use test_matrix and test jobs
  .github/workflows/test.yml
Labels: maintenance

#378 docs(README): fix app auth example
  README.md
Labels: bug, documentation
